.TH "testlab3/testlab3.cpp" 3 "testlab3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testlab3/testlab3.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBspice\fP"
.br
.RI "Класс для представления специи/добавки к блюду "
.ti -1c
.RI "class \fBdish\fP"
.br
.RI "Класс для представления блюда с добавками "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for testlab3 from the source code\&.
